set fallback := true

# default recipe to display help information
default:
  @just --list


test:
    forge test -vvv

test-deployable:
    #!/usr/bin/env bash

    KTD_PORTAL=$(forge create OptimismPortal2 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast --json --constructor-args \
    0 0 | jq -r .deployedTo)

    KTD_KAILUA_TREASURY=$(forge create KailuaTreasury --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast --json --constructor-args \
                            0x0000000000000000000000000000000000000001 \
                            0x0000000000000000000000000000000000000000000000000000000000000001 \
                            0x0000000000000000000000000000000000000000000000000000000000000001 \
                            0x01 \
                            0x01 \
                            0x01 \
                            $KTD_PORTAL \
                            0x0000000000000000000000000000000000000000000000000000000000000001 \
                            0x01 | jq -r .deployedTo)

    forge create KailuaGame --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast --constructor-args \
      $KTD_KAILUA_TREASURY \
      0x01 \
      0x01 \
      0x01 \
      0x01

coverage +ARGS="-vvv":
    forge coverage --no-match-coverage "(src/vendor|test/)" {{ARGS}}

report +ARGS="-vvv":
    just coverage --report debug > coverage.out